/**
 * Collects every interface string marked with t('…'), translate('…') or
 * msg('…') in src/ into i18n/catalog.json: the list translators work from.
 * Strings must be literals (single or double quotes) with {name} placeholders;
 * template literals are rejected so nothing escapes the catalog.
 *
 *     npm run i18n:extract
 */

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'i18n', 'catalog.json');

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : /\.(tsx?|mts)$/.test(f) ? [p] : [];
  });
}

const CALL = /\b(?:t|translate|msg)\(\s*(['"])((?:\\.|(?!\1)[^\\])*)\1\s*[,)]/g;
const BAD = /\b(?:t|translate|msg)\(\s*`/g;
const strings = new Map<string, Set<string>>();
const problems: string[] = [];
for (const file of walk(SRC)) {
  if (file.includes(`${join('src', 'i18n')}`)) continue;
  const text = readFileSync(file, 'utf8');
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  for (const m of text.matchAll(CALL)) {
    const s = m[2].replace(/\\(['"\\])/g, '$1');
    if (!s.trim()) continue;
    if (!strings.has(s)) strings.set(s, new Set());
    strings.get(s)!.add(rel);
  }
  for (const m of text.matchAll(BAD)) problems.push(`${rel}: template literal passed to a translation call at offset ${m.index}`);
}
const catalog = Object.fromEntries([...strings.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([s, files]) => [s, [...files].sort()]));
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify({ about: 'English interface strings (key = text). Values: files using them. Generated by scripts/i18n-extract.ts.', strings: catalog }, null, 1) + '\n');
console.log(`i18n catalog: ${strings.size} strings -> ${relative(ROOT, OUT)}`);
if (problems.length) {
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
